### PR TITLE
Testing CSS for column design

### PR DESCRIPTION
**Pull request by Qeole**
Hi, I tried to reproduce the column design from issue #11. It probably needs a bit more testing before being pushed online (only tested on Firefox), but the basic design is here to play with :)

Below is a screenshot of what I got:
whatthetrain

### CODE REVIEW

**Comment by Qeole** [comment]
Hmmm… I just realized I based my design on the first screenshot from @ryanfeeley instead of the second (and improved) one. I'll change that (tomorrow).

**Comment by Qeole** [comment]
Here we are:
whatthetrain

**Comment by ryanfeeley** [comment]
Looks great! Only quick improvement is to make the link black and perhaps a link title saying where it goes (an calendar event?)

**Comment by Qeole** [comment]
@ryanfeeley Do you mean something like this? Just a preview, I made it with CSS only (:after {content: "…" }) but the text should be added from JavaScript I guess. So it's not pushed yet:
whatthetrain
@luser What's your opinion?

**Comment by luser** [comment]
That looks pretty great! I think he meant title="" on the link, not actual text there.

**Comment by Qeole** [comment]
Oh yeah, makes sense.
I fixed and pushed it, it's live at https://qeole.github.io/whatthetrain/ (or see the tooltip on this picture:).
whatthetrain

**Pull request merged**
